/**
 * Bundled pronunciation clips, keyed by word id. Generated by
 * `scripts/generate-voice.js` (run in CI once a TTS API key is configured — see
 * VOICE_SETUP.md). Empty by default: with no clips, the app falls back to the
 * device's text-to-speech, so it always builds and always speaks *something*.
 *
 * This file is REGENERATED by the script — do not edit the map by hand.
 */
export const VOICE: Record<string, number> = {};
