/* eslint-disable */
/**
 * Generates one consistent, natural pronunciation clip per word/phrase and
 * writes a manifest the app loads. Runs wherever the network is open (CI, or
 * your machine) — NOT inside the sandboxed session.
 *
 * Providers (pick one by which env var is set):
 *   GOOGLE_TTS_API_KEY   → Google Cloud Text-to-Speech (best Urdu voices).
 *                          Optional VOICE_NAME (default ur-IN-Wavenet-A).
 *   ELEVENLABS_API_KEY   → ElevenLabs (+ ELEVENLABS_VOICE_ID, multilingual v2).
 *
 * No key set → prints a notice and exits 0 (app keeps using device TTS).
 *
 * Run: node scripts/generate-voice.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'voice');
const MANIFEST = path.join(ROOT, 'src', 'lib', 'voiceManifest.ts');
const WORDS_TS = path.join(ROOT, 'src', 'data', 'words.ts');

// ---- collect { id, text } from the content ------------------------------
function collectItems() {
  const src = fs.readFileSync(WORDS_TS, 'utf8');
  const items = [];
  // WORDS + PHRASES share the shape { id: '...', urdu: '...', ... }
  const re = /id:\s*'([^']+)'\s*,\s*urdu:\s*'([^']+)'/g;
  let m;
  while ((m = re.exec(src))) items.push({ id: m[1], text: m[2] });
  return items;
}

// ---- providers ----------------------------------------------------------
async function googleTTS(text) {
  const key = process.env.GOOGLE_TTS_API_KEY;
  const name = process.env.VOICE_NAME || 'ur-IN-Wavenet-A';
  const res = await fetch(`https://texttospeech.googleapis.com/v1/text:synthesize?key=${key}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      input: { text },
      voice: { languageCode: 'ur-IN', name },
      audioConfig: { audioEncoding: 'MP3', speakingRate: 0.92 },
    }),
  });
  if (!res.ok) throw new Error(`Google TTS ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return Buffer.from(json.audioContent, 'base64');
}

async function elevenTTS(text) {
  const key = process.env.ELEVENLABS_API_KEY;
  const voice = process.env.ELEVENLABS_VOICE_ID;
  if (!voice) throw new Error('ELEVENLABS_VOICE_ID is required with ELEVENLABS_API_KEY');
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voice}`, {
    method: 'POST',
    headers: { 'xi-api-key': key, 'Content-Type': 'application/json', Accept: 'audio/mpeg' },
    body: JSON.stringify({ text, model_id: 'eleven_multilingual_v2' }),
  });
  if (!res.ok) throw new Error(`ElevenLabs ${res.status}: ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

function pickProvider() {
  if (process.env.GOOGLE_TTS_API_KEY) return { name: 'Google Cloud TTS', fn: googleTTS };
  if (process.env.ELEVENLABS_API_KEY) return { name: 'ElevenLabs', fn: elevenTTS };
  return null;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---- main ---------------------------------------------------------------
(async () => {
  const provider = pickProvider();
  if (!provider) {
    console.log('No TTS API key set (GOOGLE_TTS_API_KEY or ELEVENLABS_API_KEY).');
    console.log('Skipping voice generation — the app will use device TTS. See VOICE_SETUP.md.');
    process.exit(0);
  }

  const items = collectItems();
  console.log(`Generating ${items.length} clips with ${provider.name}…`);
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const done = [];
  for (const { id, text } of items) {
    try {
      const audio = await provider.fn(text);
      fs.writeFileSync(path.join(OUT_DIR, `${id}.mp3`), audio);
      done.push(id);
      console.log(`  ✓ ${id}  “${text}”  (${(audio.length / 1024).toFixed(1)} KB)`);
      await sleep(120); // gentle on rate limits
    } catch (e) {
      console.error(`  ✗ ${id}: ${e.message}`);
    }
  }

  // write the manifest (static requires so Metro bundles the files)
  const entries = done
    .map((id) => `  '${id}': require('../../assets/voice/${id}.mp3'),`)
    .join('\n');
  const contents =
    `/** AUTO-GENERATED by scripts/generate-voice.js — do not edit by hand. */\n` +
    `export const VOICE: Record<string, number> = {\n${entries}\n};\n`;
  fs.writeFileSync(MANIFEST, contents);
  console.log(`\nWrote ${done.length} clips + manifest (${path.relative(ROOT, MANIFEST)}).`);
})().catch((e) => {
  console.error('Voice generation failed:', e);
  process.exit(1);
});
